export const DEEPCLAW_OPENAI_IMAGE_PROVIDER_KEY = 'deepclaw-openai-image';
export const DEEPCLAW_OPENAI_IMAGE_DEFAULT_MODEL = 'gpt-image-2';
export const DEEPCLAW_OPENAI_IMAGE_DEFAULT_REF = `${DEEPCLAW_OPENAI_IMAGE_PROVIDER_KEY}/${DEEPCLAW_OPENAI_IMAGE_DEFAULT_MODEL}`;
