// AUTO-GENERATED by scripts/generate-brand.mjs — DO NOT EDIT BY HAND.
// Regenerated from brands/<BRAND>.json on every dev/build run.
// Committed default = "deepclaw" so type-resolution + dev work before first codegen.
import type { BrandConfig } from './types';

export const ACTIVE_BRAND: BrandConfig = {
  id: 'huanxingclaw',
  appName: 'HuanxingClaw',
  productName: 'HuanxingClaw',
  executableName: 'huanxingclaw',
  appId: 'app.huanxingclaw.desktop',
  dataDirName: '.huanxingclaw',
  instanceLockName: 'huanxingclaw',
  providerKey: 'huanxingclaw',
  serviceUrl: 'https://api.huanxing.ai',
  copyright: 'Copyright © 2026 HuanxingClaw',
  vendor: 'HuanxingClaw',
  maintainer: 'HuanxingClaw Team <support@huanxingclaw.ai>',
  linuxWMClass: 'huanxingclaw',
  tagline: 'AI Assistant',
  assetsDir: 'resources/brands/huanxingclaw',
};
