// AUTO-GENERATED by scripts/generate-brand.mjs — DO NOT EDIT BY HAND.
// Regenerated from brands/<BRAND>.json on every dev/build run.
// Committed default = "huanxingclaw" so type-resolution + dev work before first codegen.
import type { BrandConfig } from './types';

export const ACTIVE_BRAND: BrandConfig = {
  id: 'ccworkclaw',
  appName: 'CCWorkClaw',
  productName: 'CCWorkClaw',
  executableName: 'ccworkclaw',
  appId: 'site.ccwork.claw.desktop',
  dataDirName: '.ccworkclaw',
  instanceLockName: 'ccworkclaw',
  providerKey: 'ccworkclaw',
  serviceUrl: 'https://ccwork.site',
  recommendedModels: [],
  rechargeUrl: 'https://ccwork.site',
  updateFeedBaseUrl: 'https://huanxingupdate.oss-cn-beijing.aliyuncs.com/desktop-updates/ccworkclaw',
  copyright: 'Copyright © 2026 CCWorkClaw',
  vendor: 'CCWork',
  maintainer: 'CCWork Team',
  linuxWMClass: 'ccworkclaw',
  tagline: 'AI Assistant',
  logoPng: 'brands/ccworklogo.png',
  assetsDir: 'resources/brands/ccworkclaw',
};
