#!/usr/bin/env node
/**
 * Brand codegen — emits the active brand into source consumed at runtime.
 *
 * Outputs (both .gitignore-tracked-as-generated; the deepclaw default is
 * committed so dev/typecheck work before the first codegen run):
 *   shared/brand/active.generated.ts          — typed brand object (main + renderer)
 *   src/assets/brand-logo.generated.svg        — brand logo (or placeholder fallback)
 *
 * Brand selected by `BRAND` env (default "deepclaw"). Run automatically at the
 * front of predev/package/build chains, alongside generate-ext-bridge.mjs.
 *
 * Usage:  BRAND=frogclaw node scripts/generate-brand.mjs
 */
import { existsSync, readFileSync, writeFileSync, mkdirSync, copyFileSync, readdirSync } from 'fs';
import { resolve, dirname, join } from 'path';
import { fileURLToPath } from 'url';
import { loadBrand, ROOT } from './brand.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));

const ACTIVE_OUT = resolve(ROOT, 'shared/brand/active.generated.ts');
const LOGO_OUT = resolve(ROOT, 'src/assets/brand-logo.generated.svg');
const PLACEHOLDER_LOGO = resolve(ROOT, 'src/assets/logo.svg');
const CLI_SRC_DIR = resolve(ROOT, 'resources/cli');
const CLI_OUT_DIR = resolve(ROOT, 'build/cli');

/** Serialize a JSON value as an indented TS literal (single-quoted strings). */
function toTsLiteral(value, indent = 0) {
  const pad = '  '.repeat(indent);
  const padInner = '  '.repeat(indent + 1);
  if (value === null) return 'null';
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  if (typeof value === 'string') return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    const items = value.map((v) => `${padInner}${toTsLiteral(v, indent + 1)},`).join('\n');
    return `[\n${items}\n${pad}]`;
  }
  const entries = Object.entries(value)
    .map(([k, v]) => `${padInner}${k}: ${toTsLiteral(v, indent + 1)},`)
    .join('\n');
  return `{\n${entries}\n${pad}}`;
}

function emitActiveModule(brand) {
  return [
    '// AUTO-GENERATED by scripts/generate-brand.mjs — DO NOT EDIT BY HAND.',
    '// Regenerated from brands/<BRAND>.json on every dev/build run.',
    '// Committed default = "deepclaw" so type-resolution + dev work before first codegen.',
    "import type { BrandConfig } from './types';",
    '',
    `export const ACTIVE_BRAND: BrandConfig = ${toTsLiteral(brand, 0)};`,
    '',
  ].join('\n');
}

function copyLogo(brand) {
  const brandLogo = resolve(ROOT, brand.assetsDir, 'logo.svg');
  const src = existsSync(brandLogo) ? brandLogo : PLACEHOLDER_LOGO;
  if (!existsSync(src)) {
    console.warn(`[brand] No logo found for "${brand.id}" and no placeholder at ${PLACEHOLDER_LOGO}.`);
    return false;
  }
  mkdirSync(dirname(LOGO_OUT), { recursive: true });
  copyFileSync(src, LOGO_OUT);
  return src === brandLogo;
}

/**
 * Resolve CLI wrapper templates (placeholders → brand values) into build/cli/.
 * The packaged app copies from build/cli (see electron-builder.yml) so each
 * brand's wrappers point at its own executable (e.g. frogclaw.exe).
 */
function generateCliWrappers(brand) {
  const replace = (text) =>
    text
      .replaceAll('__BRAND_NAME__', brand.appName)
      .replaceAll('__BRAND_PRODUCT__', brand.productName)
      .replaceAll('__BRAND_EXE__', brand.executableName)
      .replaceAll('__BRAND_DATA_DIR__', brand.dataDirName);

  let count = 0;
  for (const platform of ['posix', 'win32']) {
    const srcDir = join(CLI_SRC_DIR, platform);
    const outDir = join(CLI_OUT_DIR, platform);
    if (!existsSync(srcDir)) continue;
    mkdirSync(outDir, { recursive: true });
    for (const file of readdirSync(srcDir)) {
      writeFileSync(join(outDir, file), replace(readFileSync(join(srcDir, file), 'utf-8')));
      count++;
    }
  }
  return count;
}

// ─── Main ───
const brand = loadBrand();

mkdirSync(dirname(ACTIVE_OUT), { recursive: true });
writeFileSync(ACTIVE_OUT, emitActiveModule(brand));

const usedBrandLogo = copyLogo(brand);
const cliCount = generateCliWrappers(brand);

console.log(
  `[brand] Generated active brand "${brand.id}" (${brand.appName}) → ` +
    `${brand.executableName}.exe, appId ${brand.appId}, data ~/${brand.dataDirName}` +
    (usedBrandLogo ? '' : ' [logo: placeholder]') +
    ` [${cliCount} CLI wrappers]`,
);
